name=Modbus_Manager
version=1.0.0
author=Ade Firman
maintainer=Ade Firman <adilllfirman@gmail.com>
sentence=Library wrapper Modbus RTU yang elegan, type-safe, dan dilengkapi auto-pin RS485.
paragraph=Modbus Manager menyederhanakan library ModbusMaster dengan menggunakan C++ function overloading untuk menangani baca/tulis tipe data uint16, int16, uint32, int32, dan float secara otomatis. Dilengkapi dengan kontrol pin DE/RE otomatis dan sistem pengembalian status boolean untuk error handling yang bersih.
category=Communication
url=https://github.com/0ADILL3/Modbus_Manager
architectures=*
depends=ModbusMaster
includes=Modbus_Manager.h